#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=AMRCT -- '*.go')

if [[ $STAGED_GO_FILES != "" ]]; then
	for file in $STAGED_GO_FILES; do
		go fmt $file
		git add $file
	done
fi
